/*
 * Font file based on autogenerated file from FontLeroy (a Windows
 * application).
 *
 * Various fonts are implemented by supplying specific definitions of the below
 * arrays. See src/fonts/courier.c for an example. Fonts are selected by
 * linking with the desired font source file.
 */

#ifndef FGUI_FONT_DATA_H
#define FGUI_FONT_DATA_H

#include <stdint.h>
#include <stdlib.h>  /* wchar_t */

// Grid size is 7 across by 9 down
// Scan order is horizontal, L->R, start at top
// Output is padded bytes, right adjusted
// Blanks encoded as 7 by 9
//
// These are the decimal ASCII values that are encoded:
extern uint8_t cAscii[62];

// Width and height of the characters in bits:
extern uint8_t cWidth[62];
extern uint8_t cHeight[62];

// These are the 0 based offsets for each character:
extern uint16_t cOff0[62];

// These are the 1 based offsets for each character:
extern uint16_t cOff1[62];

// This is the encoded data for each character:
extern uint8_t cData[558];

//struct font_data {
//	wchar_t codepoint;
//	int width;
//	int height;
//	unsigned char data[50];  // FIXME: wastes space!
//};

//extern struct font_data cUnicode[62];

#endif /* FGUI_FONT_DATA_H */
